parameters:
  - name: jobName
    type: string
  - name: vmImage
    type: string
  - name: solution
    type: string
    default: '**/*.sln'
  - name: buildPlatform
    type: string
    default: 'Any CPU'
  # - name: buildConfiguration
    # type: string
    # default: 'Debug'
  - name: projects
    type: string
    default: '**/*Tests/*.csproj'
  - name: netVersion
    type: string
    default: '6.0.x'
  - name: install_PS7_Steps
    type: stepList
    default: []



jobs:
  - job: ${{ parameters.jobName }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
        matrix:
          Debug:
            buildConfiguration: 'Debug'
          Release:
            buildConfiguration: 'Release'
    
    steps:
      - ${{ each step in parameters.install_PS7_Steps }}:
      # build
      - template: steps_build.yml
        parameters:
          solution: ${{ parameters.solution }}
          buildPlatform: ${{ parameters.buildPlatform }}
          buildConfiguration: $(buildConfiguration)
          netVersion: ${{ parameters.netVersion }} 
      # tests
      - template: steps_tests.yml
        parameters:
          projects: ${{ parameters.projects }}
          netVersion: ${{ parameters.netVersion }}
          buildConfiguration: $(buildConfiguration)
