parameters:
  - name: jobName
    type: string
  - name: vmImage
    type: string
  - name: pre_CI_Steps
    type: stepList
    default: []
  - name: execution
    type: string
    values:
      - 'true'
      - 'false'
    # default: true

jobs:
  - job: ${{ parameters.jobName }}
    condition: eq('${{ parameters.execution }}', 'true')
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
       # pre-ci steps
      - ${{ each step in parameters.pre_CI_Steps }}:
        - ${{ each pair in step }}:
            ${{ pair.key }}: ${{ pair.value }}
      # build
      - template: steps_build.yml
      # tests
      - template: steps_tests.yml
