parameters:
  - name: projects
    type: string
  - name: netVersion
    type: string
    values:
      - 'net6.0'
  - name: buildConfiguration
    type: string
    # default: 'Debug'
    values:
      - Debug
      - Release


steps:
  - task: DotNetCoreCLI@2
    name: DisplayTests
    inputs:
      command: 'test'
      projects: ${{ parameters.projects }}
      arguments: '-t -f ${{ parameters.netVersion }} --configuration $(buildConfiguration)'
      publishTestResults: false
      testRunTitle: 'Display test'
  - task: DotNetCoreCLI@2
    name: RunTests
    inputs:
      command: 'test'
      projects: ${{ parameters.projects }}
      arguments: '-f ${{ parameters.netVersion }} --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
      testRunTitle: 'RunTests-$(Build.BuildNumber)'
  ## CodeCov
  - template: steps_codecov.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
  ##
  - pwsh: |
      echo $PWD
      Copy-Item ..\..\..\PowerDir.GetPowerDir.psd1 .
      Import-Module  .\PowerDir.GetPowerDir.psd1
      ../../../../runtime-tests.ps1
    workingDirectory: $(System.DefaultWorkingDirectory)/PowerDir/bin/$(buildConfiguration)/${{ parameters.netVersion }}
    name: RunTimeTests
