steps:
  - pwsh: echo $(buildConfiguration)
    name: BuildConfigurationInfo
    condition: eq(variables.debug_info, 'true')
  # prepare
  - task: UseDotNet@2
    inputs:
      version: $(useNetVersion)
      packageType: 'runtime'
      # installationPath: $(Agent.TempDirectory)
  - task: UseDotNet@2
    inputs:
      version: $(useNetVersion)
      packageType: 'sdk'
      # installationPath: $(Agent.TempDirectory)
    # info
  - pwsh: $PSVersionTable
    name: PSVersionTable
  - script: dotnet --info
    name: dotnet_info
  - script: dotnet msbuild -version
    name: MSBuild_info
  # build
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: $(solution)
  - task: VSBuild@1
    inputs:
      solution: $(solution)
      platform: $(buildPlatform)
      configuration: $(buildConfiguration)
    # continueOnError: true
    condition: eq(variables['Agent.OS'], 'Windows_NT')
  - task: MSBuild@1
    inputs:
      solution: $(solution)
      platform: $(buildPlatform)
      configuration: $(buildConfiguration)
      # clean: true
    continueOnError: true
    condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
