# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

variables:
  template: variables/images.yml

stages:
- stage: CI
  jobs:
    - template: templates/jobs_ci.yml
      parameters:
        jobName: "Windows"
        vmImage: ${{ variables.windows_image }}
    - template: templates/jobs_ci.yml
      parameters:
        jobName: "Linux"
        vmImage: ${{ variables.linux_image }}
    - template: templates/jobs_ci.yml
      parameters:
        jobName: "MacOS"
        vmImage: ${{ variables.mac_image }}
