# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  netVersion: 'net6.0'

steps:
- pwsh: $PSVersionTable
- powershell: $PSVersionTable
  

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- pwsh: |
    ls
    Import-Module  .\PowerDir.GetPowerDir.psd1
    d -d dl
  workingDirectory: PowerDir/bin/$(buildConfiguration)/$(netVersion)
  name: SmokeTest

- script: $host.Version
  condition: always()

- script: dotnet --info
  condition: always()
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '-t -f $(netVersion) --configuration $(buildConfiguration)'
    publishTestResults: false
    testRunTitle: 'Display test'
  condition: always()
- task: DotNetCoreCLI@2
  condition: always()
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '-f $(netVersion) --configuration $(buildConfiguration)'
    testRunTitle: 'run tests $(Build.BuildNumber)'
